---
version: '2'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: blacksun
      POSTGRES_PASSWORD: blacksun
      POSTGRES_DB: blacksundb
      PGDATA: /data/postgres
    volumes:
        - postgres:/data/postgres
        - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
